/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.JOptionPane;
/**
 *
 * @author miria
 */
public class FCount extends javax.swing.JFrame {
int intercambios;
    int comparaciones;
    int[] arregloOriginal;
    int[] arregloAuxiliar;
    int[] arregloOrdenado;
    int valorMayor;
    
    /**
     * Creates new form FCount
     */
    public FCount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblArregloOrdenado = new javax.swing.JLabel();
        txtMaximo = new javax.swing.JTextField();
        lblArregloInvertido = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTiempo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnArreglo = new javax.swing.JButton();
        btnArreglo2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTamaño = new javax.swing.JTextField();
        lblArregloDesordenado = new javax.swing.JLabel();
        txtMinimo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblArregloOrdenado.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblArregloOrdenado.setText("-");

        txtMaximo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        lblArregloInvertido.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblArregloInvertido.setText("-");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setText("Min");

        lblTiempo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblTiempo.setText("-");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setText("Max");

        btnRegresar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnRegresar.setText("VOLVER");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnArreglo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnArreglo.setText("Crear arreglo");
        btnArreglo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArregloActionPerformed(evt);
            }
        });

        btnArreglo2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnArreglo2.setText("Crear arreglo aleatorio");
        btnArreglo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArreglo2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setText("Arreglo desordenado");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setText("Arreglo ordenado");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel10.setText("Arreglo invertido");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setText("Tamaño del arreglo");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel11.setText("Tiempo elapsado");

        txtTamaño.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        lblArregloDesordenado.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblArregloDesordenado.setText("-");

        txtMinimo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("COUNT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnArreglo2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnArreglo))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblArregloDesordenado)
                            .addComponent(lblArregloOrdenado)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblArregloInvertido)
                                    .addComponent(lblTiempo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                                .addComponent(btnRegresar)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnArreglo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4))
                    .addComponent(btnArreglo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblArregloDesordenado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblArregloOrdenado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblArregloInvertido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblTiempo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnArregloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArregloActionPerformed
        try
        {
            int tamaño = Integer.parseInt(txtTamaño.getText());
            int minimo = Integer.parseInt(txtMinimo.getText());
            int maximo = Integer.parseInt(txtTamaño.getText());
            if (tamaño <= 0)
            {
                JOptionPane.showMessageDialog(null,"El tamaño no puede ser menor o igual a 0");
                return;
            }
            if(maximo <= minimo)
            {
                JOptionPane.showMessageDialog(null, "El maximo no puede ser menor o igual que el minimo");
                return;
            }
            txtMaximo.setText("");
            txtMinimo.setText("");
            txtTamaño.setText("");
            intercambios = 0;
            comparaciones = 0;
            OrdenarArreglo(tamaño,minimo,maximo);

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Introduzca datos validos");
        }
    }//GEN-LAST:event_btnArregloActionPerformed
private String ImprimirArreglo(int[] arreglo){
        String numeros = "";
        if(arreglo.length != 0){
            for (int i = 0; i< arreglo.length;i++){
                numeros += arreglo[i] + ", ";
            }
        }
        return numeros;
    }
     
     public void OrdenarArreglo(int tamaño,int minimo, int maximo){
         arregloOriginal = new int[tamaño];
        long start = System.nanoTime();
            int random;
            for (int i = 0; i < arregloOriginal.length; i++)
            {
               random  = ThreadLocalRandom.current().nextInt(minimo,maximo + 1);
               arregloOriginal[i] = random;
            }
            lblArregloDesordenado.setText(ImprimirArreglo(arregloOriginal));
            
            for (int i = 0; i < arregloOriginal.length; i++)
            {
                if (arregloOriginal[i] > valorMayor)
                {
                    valorMayor = arregloOriginal[i];
                }
            }

            arregloAuxiliar = new int[valorMayor + 1];
            int posicion;
            for (int i = 0; i < arregloOriginal.length; i++)
            {
                posicion = arregloOriginal[i];
                arregloAuxiliar[posicion]++;
            }

            for (int i = 1; i < arregloAuxiliar.length; i++)
            {
                arregloAuxiliar[i] = arregloAuxiliar[i - 1] + arregloAuxiliar[i];
            }   

            for (int i = arregloAuxiliar.length - 1; i != 0; i--)
            {
                arregloAuxiliar[i] = arregloAuxiliar[i - 1];
            }
            arregloAuxiliar[0] = 0;

            arregloOrdenado = new int[arregloOriginal.length];
            int valor;  
            for (int i = 0; i < arregloOriginal.length; i++)
            {
                valor = arregloOriginal[i];
                posicion = arregloAuxiliar[valor];
                arregloOrdenado[posicion] = valor;
                arregloAuxiliar[valor]++;
            }
            long aaa;
            aaa = System.nanoTime();
            double tiempo = (aaa - start)/1000000.0;
            lblTiempo.setText(tiempo + "");
            lblArregloOrdenado.setText(ImprimirArreglo(arregloOrdenado));
            RevertirArreglo();
            lblArregloInvertido.setText(ImprimirArreglo(arregloOrdenado)); 
            
            
            
     }
    private void btnArreglo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArreglo2ActionPerformed
        int tamaño = ThreadLocalRandom.current().nextInt(1,18 + 1);
        int minimo = ThreadLocalRandom.current().nextInt(0,50 + 1);
        int maximo = ThreadLocalRandom.current().nextInt(minimo, 100 + 1);
        comparaciones = 0;
        intercambios = 0;
        OrdenarArreglo(tamaño,minimo,maximo);
    }//GEN-LAST:event_btnArreglo2ActionPerformed
public void RevertirArreglo(){
    for(int i=0; i<arregloOrdenado.length/2; i++){
  int temp = arregloOrdenado[i];
  arregloOrdenado[i] = arregloOrdenado[arregloOrdenado.length -i -1];
  arregloOrdenado[arregloOrdenado.length -i -1] = temp;
}
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FCount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FCount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FCount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FCount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FCount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArreglo;
    private javax.swing.JButton btnArreglo2;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblArregloDesordenado;
    private javax.swing.JLabel lblArregloInvertido;
    private javax.swing.JLabel lblArregloOrdenado;
    private javax.swing.JLabel lblTiempo;
    private javax.swing.JTextField txtMaximo;
    private javax.swing.JTextField txtMinimo;
    private javax.swing.JTextField txtTamaño;
    // End of variables declaration//GEN-END:variables
}
